import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <nav className='bg-gray-800 flex justify-between px-10 py-6 text-white'>
          <h1>Video<strong className='bg-gray-100 p-1 rounded-lg text-black ml-2'>PRO</strong></h1>
          <h5>More information</h5>
        </nav>
        <p>Stand out from the crowd with our video converter pro - the ultimate solution for company&apos;s social networks.</p> 
      </main>
    </>
  )
}
